### ISSUE TITLE
404 on flixel->ui->PxButton at api.haxeflixel.com

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/haxeflixel.com#103]
links to http://api.haxeflixel.com/flixel/ui/PxButton.html

**Comment by Gama11** [comment]
Well, yeah. that class doesn't exist anymore in 4.0.0. How did you find that page? Shouldn't be reachable via the navigation.

**Comment by GimmickyApps** [comment]
That's what I mean by the title.  It *is* reachable by the navigation.  Click flixel, then ui, and PxButton is the last leaf.

**Comment by Gama11** [comment]
Not for me. Try refreshing the cache.

**Comment by GimmickyApps** [comment]
You're right.  I hadn't thought it would be a caching issue, since I had restarted my browser since the release.  Thanks.
