### ISSUE TITLE
flixel/addons/ui/FlxUISpriteButton.html exists but FlxUISpriteButton no longer does

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/haxeflixel.com#104]
1. start at http://api.haxeflixel.com/flixel/FlxSprite.html
1. click  FlxTypedButton
1. click  FlxUITypedButton
1. click FlxUISpriteButton
...but FlxUISpriteButton is nowhere to be found in the flixel-addons source

**Comment by Gama11** [comment]
That's because it's [part of flixel-ui](https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/FlxUISpriteButton.hx), not flixel-addons (you can also click "view source" in the upper right of the page).

Btw, the flixel-docs repo is responsible for API issues.

**Comment by GimmickyApps** [comment]
It says "package flixel.addons.ui"...OK, I find that confusing.  Sorry for the wrong repo, I forgot about that too.

**Comment by GimmickyApps** [comment]
"View source" works great, I'll use that from now on.  Thanks.

**Comment by Gama11** [comment]
flixel-ui uses the `flixel.addons.ui` package. It was chosen because `flixel.ui` would be even more confusing, considering that's used for core flixel classes like `FlxButton`. And in a way, flixel-ui is just "more addons".

**Comment by larsiusprime** [comment]
We could always rename it flixel-GUI, but then that'd be a breaking change, even if it's only one letter.

**Comment by Gama11** [comment]
That seems like a bad idea. There'd still be `flixel.ui` and `flixel.addons.ui` packages in flixel and flixel-addons respectively, and those are technically for GUI as well.

**Comment by GimmickyApps** [comment]
Maybe there's not a clean way around the confusion.  Even if you called everything in flixel-addons, um, `flixel-addons.*`, there will still be parallels and confusion.  To me the simplest way out of the confusion was the View Source button.  The simplest way into it was trying to guess which repo it came from from the package name.  :)

**Comment by Gama11** [comment]
Hm.. I could imagine displaying a link to haxelib there as well, indicating which haxelib library the type you're currently looking at belongs to.
