### ISSUE TITLE
[Forum]: Enable SSO options

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFlixel/haxeflixel.com#108]
Things to enable:
- [ ] Github
- [ ] Twitter
- [ ] Google
- [ ] Facebook (?)

This requires that a Flixel owner set up an "app" entry with each of these services for "HaxeFlixel" forum and enter the credentials in the nodeBB backend. Presumably the account should be under the control of the relevant HaxeFlixel account on that service. We have HaxeFlixel accounts for Github and Twitter, do we have anything on Google and Facebook?

**Comment by Gama11** [comment]
>do we have anything on Google and Facebook?

No.

**Comment by Gama11** [comment]
Actually, disregard that, there is a Google account.

**Comment by nospoone** [comment]
Here are the links for the SSO apps:

- [GitHub](https://github.com/settings/applications/new)
  - Callback URL: {forum's future url}/auth/github/callback
- [Twitter](https://apps.twitter.com/)
  - Callback URL: {forum's future url}/auth/twitter/callback
- [Google](https://code.google.com/apis/console/)
    - Ensure you have the "Google+ API" enabled in your API console settings.
    - Redirect URI: {forum's future url}/auth/github/callback
- [Facebook](https://developers.facebook.com/apps/)

I strongly suggest doing the extra mile for Facebook!

**Comment by larsiusprime** [comment]
I'd vote for doing everything, too. At least if the goal is to grow the community :)

**Comment by larsiusprime** [comment]
I have set up the GitHub application, and transferred ownership of it to the Github HaxeFlixel organization.

**Comment by larsiusprime** [comment]
Shoot, twitter requires you associate a mobile phone with the account to set up an Oauth app. In that case I might have to create it with larsiusprime rather than HaxeFlixel, b/c otherwise you'll all need my phone to 2-factor into the twitter account.

**Comment by larsiusprime** [comment]
Okay twitter is set up under my own account, contact me for details, @nospoone

**Comment by larsiusprime** [comment]
Okay google is set up under the HaxeFlixel account
