### ISSUE TITLE
[Forum]: install akismet / anti-spam

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFlixel/haxeflixel.com#111]
We need to install the akismet plugin or other relative anti-spam countermeasure

**Comment by nospoone** [comment]
Here's what we can enable:
- [Akismet](https://akismet.com/): not free, but works.
- [Project Honeypot](http://www.projecthoneypot.org/): free, stops bot registrations.
- [Recaptcha](http://www.google.com/recaptcha): free, adds a (new style) recaptcha to user registrations

**Comment by larsiusprime** [comment]
I already have an akismet plan, wonder if I can double dip

**Comment by nospoone** [comment]
It says _Single Site_ on the website, but you can try dropping your key in the plugin: 

Dashboard > Plugins > Spam Be Gone

Not sure if it's going to give you an error right away or just fail silently.

**Comment by larsiusprime** [comment]
hmmm they want another $59 / year for a second site. Happy to do it, honestly. They seem to have a free option tho?

**Comment by larsiusprime** [comment]
Okay got a $12/yr plan for "noncommercial" usage.

**Comment by larsiusprime** [comment]
Akismet enabled. Can you enable the other two?

**Comment by nospoone** [comment]
Sure, but I'll be the owner of the accounts. #112?

**Comment by larsiusprime** [comment]
Yeah, just create new accounts for them from now. We can always change the internal account details to something under "central" haxeflixel control later.

**Comment by nospoone** [comment]
All available anti-spam systems are now enabled!

**Comment by larsiusprime** [comment]
Magnificent. We'll see what the UX is like and if necessary we can dial it down, but it pays to start out safe.
