### ISSUE TITLE
[Forum]: Categories

### ISSUE THREAD

**Issue by nospoone** [HaxeFlixel/haxeflixel.com#113]
We need to add proper categories. Here's my ideas:

- Announcements
- General Discussion
- Help
- Games (or Showoff? Showcase? - something to show your wip/completed game)

**Comment by larsiusprime** [comment]
"Show your stuff" perhaps -- combination of showcase and devlogs?

**Comment by nospoone** [comment]
Yes, but we could also potentially split these maybe?

**Comment by larsiusprime** [comment]
Yeah, perhaps. I like TIGSource-style devlogs, those can be really fun, and it would be nice to separate those from "MY COOL GAME IS OUT LOOK AT IT ITS GREAT!" posts, which might need their own category.

About "announcements" -- is that for US to announce, or for developers to announce their own projects? Maybe we should call it "News" ?

**Comment by nospoone** [comment]
It'd be for us: _HaxeFlixel 4.0 is out now on Haxelib_. That kind of thing.

**Comment by larsiusprime** [comment]
Perfect. Okay, I think these are good categories then:

- Announcements (locked to admins to create new posts, that should make it clear enough)
- General Discussion 
- Help
- Showcase
- Dev Logs

**Comment by nospoone** [comment]
Done!
