### ISSUE TITLE
Visual Studio Code section of Getting Started does not work

### ISSUE THREAD

**Issue by mikeevmm** [HaxeFlixel/haxeflixel.com#137]
From [Getting Started > Visual Studio Code](http://haxeflixel.com/documentation/visual-studio-code/)

> [...]
> The Haxe extension requires Haxe 3.3.0-rc1 or newer.
> [...]
> ## Code Completion
If you've correctly installed the Haxe extension and are using a Haxe version higher > 3.3.0, it should work out of the box.

This is impossible as of now, since HaxeFlixel does not compile (for, at least, cpp) in Haxe 3.3.0-rc1.

**Comment by Gama11** [comment]
Sure it does. What problems are you experiencing?

**Comment by mikeevmm** [comment]
This error is specific to my current project, but I've always got a variant of it in any project I try to compile.

```CMD
GameState.cpp
./src/states/GameState.cpp(735) : error C2039: 'Z' : is not a member of 'flixel::FlxBasic_obj'
        E:\Documents\Flash Develop Projects\Goody Two Shoes\GTS\export\windows\cpp\obj\include\flixel/FlxBasic.h(19) : see declaration of 'flixel::FlxBasic_obj'
./src/states/GameState.cpp(739) : error C2039: 'Z' : is not a member of 'flixel::FlxBasic_obj'
        E:\Documents\Flash Develop Projects\Goody Two Shoes\GTS\export\windows\cpp\obj\include\flixel/FlxBasic.h(19) : see declaration of 'flixel::FlxBasic_obj'

Build halted with errors.
```

**Comment by Gama11** [comment]
Can you try to upgrade to a [Haxe nightly build](http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/index.html) and hxcpp from GitHub to see if the error persists? This looks like a cpp code generation bug that definitely needs to be looked into (if it's not fixed already).

**Comment by mikeevmm** [comment]
Haxe Nightly Build breaks everything very badly. About to try git hxcpp with 3.3.0-rc2 and see how that goes.

**Comment by Gama11** [comment]
Could you be a bit more specific than that? Different errors?

There is no rc2.

**Comment by mikeevmm** [comment]
Throws an error for pretty much every class that it tries to build, including some `Nape` classes I included.

Regarding rc2, download and run an rc1 installer:

![image](https://cloud.githubusercontent.com/assets/7550678/18794149/10a18288-81b6-11e6-9124-9c11de014f52.png)

**Comment by Gama11** [comment]
Are you in the HaxeFlixel slack by chance? Communicating via GitHub issues is a bit tedious...

**Comment by mikeevmm** [comment]
For future readers:

This turned out to be a Haxe problem, as shown on [this repository](https://github.com/mikeevmm/HaxeRC1-Interface-Error).

**Comment by Gama11** [comment]
Reported to Haxe: https://github.com/HaxeFoundation/haxe/issues/5705
