### ISSUE TITLE
SSL cert expired (and auto-redirects to HTTPS, so...)

### ISSUE THREAD

**Issue by codingthat** [HaxeFlixel/haxeflixel.com#157]
> This server could not prove that it is haxeflixel.com; its security certificate expired yesterday.

**Comment by codingthat** [comment]
> haxeflixel.com uses an invalid security certificate. The certificate expired on June 7, 2018, 12:53 AM

**Comment by Gama11** [comment]
Ping @impaler.

**Comment by larsiusprime** [comment]
Time to update the LetsEncrypt cert?

**Comment by codingthat** [comment]
@larsiusprime I think so (and maybe add it to the annual calendar of whoever has access ;) ).  I pinged @impaler on Twitter too
