### ISSUE TITLE
"Page not found" for Dungeon Crawler demo on Tutorial page

### ISSUE THREAD

**Issue by TheSpydog** [HaxeFlixel/haxeflixel.com#165]
If you visit [this page](https://haxeflixel.com/documentation/tutorial/), the section where the demo should be looks as follows:
![pagenotfound](https://user-images.githubusercontent.com/8942401/79621826-c9832200-80e2-11ea-9d8f-7ffe47170cb4.PNG)

I'm guessing this is related to all the recent website changes.

**Comment by Gama11** [comment]
Oh, right, I forgot to update this. :)
