### ISSUE TITLE
Replace Flash button with HTML5 on showcase page

### ISSUE THREAD

**Issue by ninjamuffin99** [HaxeFlixel/haxeflixel.com#174]
Since Flash has been KILLED off, and as time goes on we're likely to see more well made HaxeFlixel HTML5 games, I think it's worthwhile to at the very least add in a little HTML5 button for games that have a web version.

For example, Friday Night Funkin' is very well known to have one of it's supported versions being a free web version, compiled to HTML5. However it's only buttons are the Windows, Mac, and Linux, which each link to the itch.io page of the game. I think it'd be good to showcase that HTML5 is not only possible, but show off well made examples of it.

**Comment by Gama11** [comment]
I think I wouldn't want to remove the Flash button for showcase entries that do have Flash versions. We could handle that like the console buttons, which are hidden in their "disabled state".

**Comment by polybiusproxy** [comment]
> I think I wouldn't want to remove the Flash button for showcase entries that do have Flash versions. We could handle that like the console buttons, which are hidden in their "disabled state".

why not build those demos to html5?
i tried myself

**Comment by Gama11** [comment]
This issue is about the showcase section, not the demos.

**Comment by polybiusproxy** [comment]
Oh, didn't noticed. Sorry!

**Comment by MrClogsworthYT** [comment]
> Since Flash has been KILLED off, and as time goes on we're likely to see more well made HaxeFlixel HTML5 games, I think it's worthwhile to at the very least add in a little HTML5 button for games that have a web version.
> 
> For example, Friday Night Funkin' is very well known to have one of it's supported versions being a free web version, compiled to HTML5. However it's only buttons are the Windows, Mac, and Linux, which each link to the itch.io page of the game. I think it'd be good to showcase that HTML5 is not only possible, but show off well made examples of it.

nice way to promote youre game /j

**Comment by ninjamuffin99** [comment]
> nice way to promote youre game /j

lolol, FNF was already promoted on the showcase section of HaxeFlixel! I just think that as time goes on things should shift towards showcasing HTML5 stuff too! FNF works on the web, but if you look at the HF showcase, it doesn't really mark it anywhere. Back in the day it'd be flash version, and that's how you'd tell if something was on the web! I think it's good to showcase that tech or whatever!

**Comment by MrClogsworthYT** [comment]
> > nice way to promote youre game /j
> 
> lolol, FNF was already promoted on the showcase section of HaxeFlixel! I just think that as time goes on things should shift towards showcasing HTML5 stuff too! FNF works on the web, but if you look at the HF showcase, it doesn't really mark it anywhere. Back in the day it'd be flash version, and that's how you'd tell if something was on the web! I think it's good to showcase that tech or whatever!

lmfao you actually replied

**Comment by MrClogsworthYT** [comment]
> > nice way to promote youre game /j
> 
> lolol, FNF was already promoted on the showcase section of HaxeFlixel! I just think that as time goes on things should shift towards showcasing HTML5 stuff too! FNF works on the web, but if you look at the HF showcase, it doesn't really mark it anywhere. Back in the day it'd be flash version, and that's how you'd tell if something was on the web! I think it's good to showcase that tech or whatever!

btw plz check the prs on fnf

**Comment by ninjamuffin99** [comment]
no

**Comment by MrClogsworthYT** [comment]
> no

why

**Comment by ninjamuffin99** [comment]
because you are asking me about my own personal repo in someone elses repo and that is bad manners and off topic.

**Comment by MrClogsworthYT** [comment]
k

**Comment by RichardBray** [comment]
I agree with @Gama11 it wouldn't make sense to remove the Flash button for games that don't have a HTML5 version. Guess we have the following options:

1. Remove the old Flash games from the showcase page and remove the Flash button
2. Remove the flash button for newer showcase entries, 2020 and above, and games that support HTML5

Personally I like the second option since we can keep all the legacy content.

**Comment by ninjamuffin99** [comment]
I think at the VERY least, an HTML5 button is long overdue
