### ISSUE TITLE
HaxeFlixel website doesn't seems to be available

### ISSUE THREAD

**Issue by mrcanard** [HaxeFlixel/haxeflixel.com#175]
- **Haxe version:** NA
- **Flixel version:** NA
- **OpenFL version:** NA
- **Lime version:** NA
- **Affected targets:**

HaxeFlixel website doesn't seems to be available (DNS issue)
Documentation Link : those pointing to haxeflixel.com
________________________________

**Code snippet reproducing the issue**:

Click on "Getting Started" in the documentation link of flixel

________________________________

**Observed behavior:**
DNS adress of haxeflixel.com is unavailable.

**Expected behavior:**
Viewing the "Getting Started" page of haxeflixel.com

**Comment by Gama11** [comment]
I've already informed the person who manages the domain 2 days ago, waiting to hear back from him.

**Comment by umgustavo** [comment]
There is some alternative download link?

**Comment by Gama11** [comment]
It's back up.
