### ISSUE TITLE
Randomize homepage demos

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/haxeflixel.com#21]
I think the homepage demos should consist of 6 randomnly chosen demos tagged as "homepage demo" (those being the higher-quality ones we have, and the newest ones).

@impaler: Might be that this would only work each time the site is compiled if done via .eco?

**Comment by amiruqdah** [comment]
@Gamma11 Any thoughts on implementing this enhancement? I might try my hand, if this still sounds like a good idea.

**Comment by impaler** [comment]
This kind of js foo would be easier to implement in a rewrite to react or similar. Since this is a static site we could generate a json file of the demos and then use some js to get a random selection.

**Comment by Gama11** [comment]
I'm not really interested in this feature anymore.
