### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by impaler** [HaxeFlixel/haxeflixel.com#3]
I am thinking we should maybe we should start using the github gist system. We could embed them using https://github.com/docpad/docpad-plugin-gist under a new documentation folder. old.haxeflixel.com/snippets

**Comment by Gama11** [comment]
[haxeflixel-mechanics](https://github.com/HaxeFlixel/haxeflixel-mechanics) is based around the idea of small code snippets, so I think this can be closed.
