### ISSUE TITLE
Documentation: Add anchors to <h>-tags

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/haxeflixel.com#35]
That way, you can link to an invidual section.

**Comment by RichardBray** [comment]
I'm guessing this ticket is closed as well since we've ruled out adding logic to the client-side?

**Comment by Gama11** [comment]
This issue is still open.

**Comment by RichardBray** [comment]
Ah okay, so someone needs to make a docpad plugin with this functionality. I don't know how easy it is to create a docpad plugin but I feel like it might be easier to create a custom npm package. I might look into this.
