### ISSUE TITLE
Create new section combining Demos, Tutorials, and Snippets into one, complete package

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/haxeflixel.com#88]
Alright, I was trying to knock out a few more demos lately, and an idea started taking form.
I think the current state of the website, demos, and turorial is not 'good enough' to help teach people about HaxeFlixel.
Sure, we can keep adding new demos to illustrate specific concepts, but I honestly don't think that's very helpful - if someone wants to understand how to do something, say, figuring out Emitters, they have to try to dig through the source code for the demo and/or trial and error to figure it out.
I think we can/should do better.

I propose adding a new section to the website, which would be sort of a combination comprehensive tutorial, feature-showcase, and mechanics explorer. 
I know that something was [started on before ](http://gme.kasoki.de/) - which was based on [something else](http://gamemechanicexplorer.com/), but, what I have in mind is something much simpler, and more complete.

Something along the lines of a huge tree of categorized concepts that get more and more complex, covering everything we can think of, complete with the most BASIC code to get the concept running and a simple demo (swf? HTML doesn't seem to be ideal, yet) for each concept.

As each concept expands and adds more complexity, it can eventually become full demonstrations of complete game genres: a space shooter, a platformer, etc.

The main goals for this project are to include a friendly, and complete answer to the following questions:
* How do I get started?
* How do I do X?
* What else can I do?

Since I'm not working on any game projects at the moment, I'd like to jump in and begin building this asap, but I'd like to have some help both in designing it, defining some principals to work with, and in figuring out which concepts to cover, etc.

And I'd like to get a bit more feedback, opinions, and discussion before starting it, too. So, yeah... what do you think?

**Comment by RafaelOliveira** [comment]
I think that Phaser has a good example:
http://phaser.io/examples
It cover everything with small code samples.

**Comment by SeiferTim** [comment]
Yeah, the phaser examples would be a good model to base some of it on.

**Comment by SeiferTim** [comment]
Some thoughts on sort of the 'rules' for what should be included in here:

Terminology:
Just the terms that have come up in my head that I'm using now, I would like to refine them later
* Concept - an idea, feature, etc that we want to demonstrate.
Example: Collision
* Item - a sub-section to the Concept, each item will demonstrate something about the Concept for the reader to see how it works. They should get more complex as the reader goes deeper into a Concept.
Each item will contain: 
 * Synopsis - friendly text explaining what this item is all about and how it relates to the overall Concept
 * Demo - a simple swf of the item being demonstrated
 * Code - colored/formatted snippets of code explaining how the demo was made
 * Source - link to the source for the demo for someone to browse it/download it/etc (github?)
 * Tags - tags, keywords, etc to assist in searching
 * Version (maybe) - which version of HaxeFlixel this item works with (dev vs live? possibly)

An example concept with items might be:
* Collision
 * Simple 1-1 Collision
 * 1-many Collision
 * Many-many Collision
 * etc

* Each item should build off of the one that precedes it, within the same concept.
For example: If we have a concept for "Collision", we would start at the most basic level with the first item - colliding two objects, and then the next item would be more complex - colliding a group, etc.
* Each item should be as simple as possible to convey the concept.
We shouldn't have emitters and particles and crazy effects when discussing the basic object-vs-object collision - that's stuff that belongs in a demo to show it all off.
* Each item should use a similar style and format.
This will help build familiarity. If the first item shows a red block for the 'player' object, ALL other items should use the same graphic, unless it's unfeasible for the concept being discussed (showing how to load an animated sprite, for example, might replace the player sprite for that one item - it should revert to the basic red block on other items, however.) This will help enforce familiarity to the reader - both in the samples and the code, if we always load the player object in the same way, and keep is as simple as possible, when the reader encounters more advanced code that is dealing with a different concept, they will be able to recognize, and skip over the now-familiar code and identify the new logic. This means we will need to come up with a style-guide to help keep everything looking uniform...

**Comment by SeiferTim** [comment]
Okay, I've started talking things out over in a new repo, everyone, let me know what you think so far: https://github.com/SeiferTim/haxeflixel-mechanics/wiki

**Comment by Gama11** [comment]
Any further discussion should probably happen at the mechanics repo.
