### ISSUE TITLE
Add a Patreon widget/link to the site's header and Main page

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/haxeflixel.com#91]
And also make it a pinned subject in the Google Group. 

It's almost as if you don't want people to know about it ;)

**Comment by gamedevsam** [comment]
Good point, I'll reach out to Chris to see if this is something he could do.

**Comment by impaler** [comment]
So I added it to the home page and footer. I am not a fan of ads in the site's header, but I am open to it if the community thinks its necessary.

**Comment by Gama11** [comment]
I think the one on the home page is a little too prominent / big... I think it would fit better in the section with the GitHub and Twitter buttons, and about that same size.

The one in the footer feels a little out of place... Maybe we can take some inspiration from http://www.openfl.org/, the icons in their footer are nice and consistent.
