### ISSUE TITLE
Error running 'haxelib run lime setup'

### ISSUE THREAD

**Issue by samncrowley** [HaxeFlixel/haxeflixel.com#97]
So I've just been trying out HaxeFlixel for the first time today and have not been able to resolve this...

I'm running Mac OS X El Capitan and when following the setup instructions, `haxelib install lime` works perfectly fine and it all installs fine, but when I run `haxelib run lime setup` I get this error:
```
Called from ? line 1
Called from CommandLineTools.hx line 1385
Called from CommandLineTools.hx line 25
Called from a C function
Called from CommandLineTools.hx line 64
Called from CommandLineTools.hx line 1082
Called from /usr/lib/haxe/std/neko/_std/sys/io/File.hx line 30
Uncaught exception - [file_contents,/haxelib.json]
```

I've been searching everywhere online and have found similar problems, but none of the solutions have worked for me.

As I'm completely new to Haxe I have no idea where to even start or what any of this means. Any ideas? Thanks! :)

**Comment by Gama11** [comment]
What Haxe version do you have / when did you install it? It should be installed in `usr/local` (see https://github.com/HaxeFoundation/haxe/issues/4585), so I'm not sure why it would be looking for `usr/lib`.

What happens when you run `haxelib path lime`?

**Comment by samncrowley** [comment]
Seems like I have version `3.2.0-rc.3`, at least that's what's said when running `haxelib version`.

`haxelib path lime` returns:
```
-L lime/2,8,2/ndll/
/Users/MYNAME/.haxelib/lime/2,8,2/
-D lime=2.8.2
```

Is that normal?

**Comment by Gama11** [comment]
So you installed Haxe a while ago already?

Either way, I'd suggest to uninstall Haxe and run the 3.2.1 (latest release) OS X Installer from [here](http://haxe.org/download/). According to that issue I linked, the paths should be fixed for that installer. Check that it has installed Haxe to `usr/local` and go through the Lime installation steps again.

**Comment by samncrowley** [comment]
Only just downloaded it today but must've accidentally got an older version. How would I uninstall Haxe in the first place?

**Comment by Gama11** [comment]
Not sure, I don't have a Mac. :) Deleting the files or just running the new installer might be good enough.

**Comment by samncrowley** [comment]
I actually already did that and ran the new installer, yet it still says I'm running version 3.2.0 and not 3.2.1. :/ happened earlier today as well when I tried installing a later version.

**Comment by Gama11** [comment]
Hm..

I'm not sure if `lime setup` does much more than set up the `lime` alias, which is really just a more convenient way to write `haxelib run lime`. Does `haxelib run lime install openfl` work? (I assume you were following [these](http://haxeflixel.com/documentation/part-i-setup/) instructions)

**Comment by samncrowley** [comment]
Actually this is probably something worth noting, but again I'm new to this and I'm not sure if it is.

Most commands I run result in getting the message `This is the first time you are runing haxelib. Please run haxelib setup first` (I just got it from running `haxelib run lime install openfl`)

When I run `haxelib setup` and hit Enter to get the default path, I get this error:
```
Failed to create directory '/usr/lib/haxelib' (std@sys_create_dir), maybe you need appropriate user rights
Check also that the parent directory exists
```

So i usually manually set the directory to just be `/Library`, which i'm sure is probably some massively fatal mistake.

And yes those are the instructions I'm following.

**Comment by Gama11** [comment]
Definitely sounds like your Haxe installation has some issues. Either way, not an issue with the documentation on haxeflixel.com, so I'm closing this issue. :)

I suggest you try posting in the OpenFL or Haxe forums. According to [this](http://community.openfl.org/t/openfl-install-fails-on-el-capitan/6596/14) you might want to try `/usr/local/lib` as the path for haxelib.
